### ISSUE TITLE
Assets not being copied into dist folder 

### ISSUE THREAD

**Issue by stumpythumb** [trungnghia112/frontend-seed-4#1]
Have tried out the seed and looks like a great starting point for working with bootstrap, sass and jquery. 

When running the build task it doesnt result with the assets being copied into the dist folder. Only copying in the core, main javascript and the compiled css file from scss source.

**Comment by trungnghia112** [comment]
I keep this folder structure. ‘Build’ the production files(css & js) and place them in the dist directory.

**Comment by Mucaccino** [comment]
How about dist the index.html?

**Comment by trungnghia112** [comment]
> How about dist the index.html?

I try to keep the current directory structure for easy inclusion in other projects using laravel, codeigniter, .... So index.html will not be in the dist directory
